name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build JAR
      run: mvn clean package -DskipTests
    
    - name: List build artifacts
      run: ls -la target/
    
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: arn:aws:iam::960005778184:role/cicd-pipeline 
        aws-region: eu-west-1
    
    - name: Subir JAR a S3
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        JAR_FILE=$(ls target/*.jar | head -n 1)
        aws s3 cp $JAR_FILE s3://terrabroker-cicd-pipeline/builds/app-$TIMESTAMP.jar
        aws s3 cp $JAR_FILE s3://terrabroker-cicd-pipeline/builds/latest.jar
        echo "✅ JAR subido a S3"
    
    - name: Desplegar la aplicacion en EC2
      env: 
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "Empezando el despliegue en EC2..."
        
        # Guardar clave SSH
        echo "$EC2_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem
        
        # SSH y ejecutar script de deploy
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \
          'bash /opt/terrabroker/deploy.sh'
        
        # Limpiar clave
        rm ec2_key.pem
        
        echo "✅ Despliegue completado!"

